# Generated by Django 5.2.7 on 2025-11-29 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('api_base', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('base_asset', models.CharField(blank=True, max_length=20, null=True)),
                ('quote_asset', models.CharField(blank=True, max_length=20, null=True)),
                ('pair_type', models.CharField(default='spot', max_length=20)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('tick_size', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('min_notional', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol'], name='dashboard_p_symbol_c2b149_idx'), models.Index(fields=['pair_type', 'symbol'], name='dashboard_p_pair_ty_0f51b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('base_asset', models.CharField(max_length=10)),
                ('quote_asset', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.exchange')),
            ],
            options={
                'unique_together': {('symbol', 'exchange')},
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('strategy_name', models.CharField(max_length=50)),
                ('parameters', models.JSONField()),
                ('total_return', models.FloatField()),
                ('sharpe_ratio', models.FloatField(blank=True, null=True)),
                ('max_drawdown', models.FloatField(blank=True, null=True)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('profit_factor', models.FloatField(blank=True, null=True)),
                ('total_trades', models.IntegerField()),
                ('avg_trade', models.FloatField(blank=True, null=True)),
                ('best_trade', models.FloatField(blank=True, null=True)),
                ('worst_trade', models.FloatField(blank=True, null=True)),
                ('total_fees', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='TradeSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('signal_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold')], max_length=4)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('indicator', models.CharField(max_length=50)),
                ('strength', models.FloatField(default=1.0)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tradingpair')),
            ],
            options={
                'indexes': [models.Index(fields=['pair', 'timestamp', 'signal_type'], name='dashboard_t_pair_id_6c34a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='OHLCVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('bollinger_upper', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('bollinger_lower', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tradingpair')),
            ],
            options={
                'indexes': [models.Index(fields=['pair', 'timestamp'], name='dashboard_o_pair_id_fe9953_idx'), models.Index(fields=['timestamp'], name='dashboard_o_timesta_57604b_idx')],
                'unique_together': {('pair', 'timestamp', 'timeframe')},
            },
        ),
    ]
