"""Add pair_ref and indicators to TradeSignal and index for pair_ref.

Generated by assistant (hand-crafted) to match models changes.
"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesignal',
            name='pair_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_signals', to='dashboard.pair'),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='indicators',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tradesignal',
            index=models.Index(fields=['pair_ref', 'timestamp', 'signal_type'], name='dashboard_t_pairre_3c9a2f_idx'),
        ),
    ]
