# Generated by Django 5.2.7 on 2025-12-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_pairref'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tradesignal',
            new_name='dashboard_t_pair_re_a4c770_idx',
            old_name='dashboard_t_pairre_3c9a2f_idx',
        ),
        migrations.AlterField(
            model_name='tradesignal',
            name='indicator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
