# Generated by Django 5.2.7 on 2026-02-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_indicators_constraint'),
        ('dashboard', '0003_rename_dashboard_t_pairre_3c9a2f_idx_dashboard_t_pair_re_a4c770_idx_and_more'),
    ]

    operations = [
    ]
