# Generated by Django 5.2.7 on 2026-02-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_remove_indicator_check"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tradesignal",
            name="dashboard_t_pair_id_6c34a0_idx",
        ),
        migrations.RemoveIndex(
            model_name="tradesignal",
            name="dashboard_t_pair_re_a4c770_idx",
        ),
        migrations.AddField(
            model_name="tradesignal",
            name="timeframe",
            field=models.CharField(default="1h", max_length=10),
        ),
        migrations.AddIndex(
            model_name="tradesignal",
            index=models.Index(
                fields=["pair", "timestamp", "signal_type", "timeframe"],
                name="dashboard_t_pair_id_a45f75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tradesignal",
            index=models.Index(
                fields=["pair_ref", "timestamp", "signal_type", "timeframe"],
                name="dashboard_t_pair_re_359a05_idx",
            ),
        ),
    ]
