# Generated by Django 5.2.7 on 2026-02-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0006_remove_tradesignal_dashboard_t_pair_id_6c34a0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestresult",
            name="timeframe",
            field=models.CharField(default="1h", max_length=10),
        ),
    ]
