# Generated by Django 5.2.7 on 2026-02-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_backtestresult_timeframe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradesignal",
            name="indicator",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
