# Generated by Django 5.2.7 on 2026-02-27 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_increase_indicator_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("GRID", "Grid Trading"),
                            ("DAYTRADING", "Day Trading"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        help_text="Configuración técnica de la estrategia"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                            ("STOPPED", "Stopped"),
                            ("ERROR", "Error"),
                        ],
                        default="STOPPED",
                        max_length=10,
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.tradingpair",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("entry_time", models.DateTimeField(auto_now_add=True)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "order_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de orden del exchange",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="dashboard.livebot",
                    ),
                ),
            ],
        ),
    ]
