# Generated by Django 5.2.7 on 2026-02-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_livebot_livetrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="livebot",
            name="last_error",
            field=models.TextField(
                blank=True, help_text="Último mensaje de error técnico", null=True
            ),
        ),
    ]
