# Generated by Django 5.2.7 on 2026-02-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_livebot_last_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='livebot',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Si es True, ejecuta órdenes reales en el exchange'),
        ),
    ]
