# Generated by Django 5.2.7 on 2026-02-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_livebot_is_live"),
    ]

    operations = [
        migrations.AddField(
            model_name="livetrade",
            name="commission",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                help_text="Comisión total pagada (entrada + salida)",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="livetrade",
            name="pnl",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                help_text="Beneficio NETO (después de comisiones)",
                max_digits=20,
            ),
        ),
    ]
