# Generated by Django 5.2.7 on 2026-02-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_livetrade_commission_alter_livetrade_pnl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livebot",
            name="status",
            field=models.CharField(
                choices=[
                    ("RUNNING", "Running"),
                    ("PAUSED", "Paused"),
                    ("CLOSE_ONLY", "Close Only"),
                    ("STOPPED", "Stopped"),
                    ("ERROR", "Error"),
                ],
                default="STOPPED",
                max_length=10,
            ),
        ),
    ]
