# Generated by Django 5.2.7 on 2026-02-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_alter_livebot_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="livetrade",
            name="exit_order_id",
            field=models.CharField(
                blank=True,
                help_text="ID de orden de salida (Sell/TP)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="livetrade",
            name="order_id",
            field=models.CharField(
                blank=True,
                help_text="ID de orden de entrada (Buy)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="livetrade",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting (Limit Buy)"),
                    ("OPEN", "Open (Position)"),
                    ("CLOSED", "Closed"),
                    ("CANCELED", "Canceled"),
                ],
                default="OPEN",
                max_length=10,
            ),
        ),
    ]
