# Generated by Django 5.2.7 on 2026-03-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_livetrade_exit_order_id_alter_livetrade_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livetrade",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
