# Generated by Django 5.2.7 on 2026-03-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_livetrade_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livetrade",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
