# Generated by Django 5.2.7 on 2026-03-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_alter_livetrade_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="livetrade",
            name="stop_loss",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="livetrade",
            name="take_profit",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=20, null=True
            ),
        ),
    ]
