# Generated by Django 5.2.7 on 2026-03-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_livetrade_stop_loss_livetrade_take_profit"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapitalFunding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("funding_date", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Transferencia desde Binance Earn",
                        max_length=200,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
