# Generated by Django 5.2.7 on 2026-03-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_capitalfunding"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_drawdown_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Porcentaje de pérdida máxima global antes de activar el Kill-Switch",
                        max_digits=5,
                    ),
                ),
                (
                    "kill_switch_active",
                    models.BooleanField(
                        default=False,
                        help_text="Si es True, ningún bot operará y todas las posiciones se cerrarán.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Global Settings",
            },
        ),
        migrations.AlterField(
            model_name="livetrade",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting (Limit Buy)"),
                    ("OPEN", "Open (Position)"),
                    ("CLOSED", "Closed"),
                    ("CANCELED", "Canceled"),
                    ("CLOSED_EMERGENCY", "Closed by Emergency"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
