# Generated by Django 5.2.7 on 2026-03-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_globalsettings_alter_livetrade_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="notifications_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Activar/Desactivar notificaciones por Telegram",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="ID del Chat de Telegram",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="telegram_token",
            field=models.CharField(
                blank=True,
                help_text="Token del Bot de Telegram",
                max_length=200,
                null=True,
            ),
        ),
    ]
