# Generated by Django 5.2.7 on 2026-03-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_globalsettings_notifications_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_balance", models.DecimalField(decimal_places=8, max_digits=20)),
                ("total_pnl", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "total_invested",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Daily Metrics",
                "ordering": ["-date"],
            },
        ),
    ]
