# Generated by Django 5.2.7 on 2026-03-14 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_dailymetric"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhaleWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("blockchain", models.CharField(default="solana", max_length=50)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WhaleTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_hash", models.CharField(max_length=255, unique=True)),
                ("timestamp", models.DateTimeField()),
                ("tx_type", models.CharField(max_length=50)),
                ("from_asset", models.CharField(blank=True, max_length=50, null=True)),
                ("to_asset", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "amount_in",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                (
                    "amount_out",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, null=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="dashboard.whalewallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatternInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern_type", models.CharField(max_length=100)),
                ("confidence", models.FloatField()),
                ("description", models.TextField()),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("meta_data", models.JSONField(blank=True, null=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="dashboard.whalewallet",
                    ),
                ),
            ],
        ),
    ]
