# Generated by Django 5.2.7 on 2026-03-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_whalewallet_whaletransaction_patterninsight"),
    ]

    operations = [
        migrations.AddField(
            model_name="whalewallet",
            name="target_token",
            field=models.CharField(
                blank=True,
                help_text="Token principal que opera (ej: JUP, PEPE)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="whalewallet",
            name="wallet_category",
            field=models.CharField(
                choices=[
                    ("DCA", "Acumulación DCA"),
                    ("SNIPER", "Sniper / Early Buyer"),
                    ("SMART_MONEY", "Smart Money"),
                    ("INSIDER", "Insider / Dev"),
                    ("OBSERVATION", "En Observación"),
                ],
                default="OBSERVATION",
                max_length=20,
            ),
        ),
    ]
