# Generated by Django 5.2.7 on 2026-03-15 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_whalewallet_target_token_whalewallet_wallet_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShadowTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_symbol", models.CharField(max_length=50)),
                ("token_mint", models.CharField(blank=True, max_length=255, null=True)),
                ("entry_price", models.DecimalField(decimal_places=10, max_digits=30)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Cantidad simulada en el token",
                        max_digits=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Abierta"), ("CLOSED", "Cerrada")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("pnl_percent", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadow_trades",
                        to="dashboard.whalewallet",
                    ),
                ),
            ],
        ),
    ]
