# Generated by Django 5.2.7 on 2026-03-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_shadowtrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="whalewallet",
            name="filter_mode",
            field=models.CharField(
                choices=[
                    ("OPEN", "Todo (Pumps & Stables)"),
                    ("STRICT", "Solo Estables (Whitelist)"),
                ],
                default="OPEN",
                max_length=10,
            ),
        ),
    ]
