# Generated by Django 5.2.7 on 2026-03-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0025_whalewallet_filter_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whalewallet",
            name="blockchain",
            field=models.CharField(
                choices=[
                    ("solana", "Solana"),
                    ("ethereum", "Ethereum"),
                    ("base", "Base"),
                ],
                default="solana",
                max_length=50,
            ),
        ),
    ]
