# Generated by Django 5.2.7 on 2026-03-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0026_alter_whalewallet_blockchain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whalewallet",
            name="blockchain",
            field=models.CharField(
                choices=[
                    ("solana", "Solana"),
                    ("ethereum", "Ethereum"),
                    ("base", "Base"),
                    ("hyperliquid", "Hyperliquid"),
                ],
                default="solana",
                max_length=50,
            ),
        ),
    ]
