# Generated by Django 5.2.7 on 2026-03-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_alter_whalewallet_blockchain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whalewallet",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="whalewallet",
            unique_together={("address", "blockchain")},
        ),
    ]
