# Generated by Django 5.2.7 on 2026-03-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_alter_whalewallet_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whalewallet",
            name="last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whalewallet",
            name="sync_status",
            field=models.CharField(
                default="IDLE",
                help_text="Estado de la sincronización en background",
                max_length=20,
            ),
        ),
    ]
