# Generated by Django 5.2.7 on 2026-03-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_whalewallet_last_sync_whalewallet_sync_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="whalewallet",
            name="top_tokens",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
