# Generated by Django 5.2.7 on 2026-03-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0030_whalewallet_top_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="shadowtrade",
            name="market_context",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whalewallet",
            name="trading_dna",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
