# Generated by Django 5.2.7 on 2026-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_shadowtrade_market_context_whalewallet_trading_dna'),
    ]

    operations = [
        migrations.AddField(
            model_name='whalewallet',
            name='target_pairs',
            field=models.CharField(blank=True, help_text='Tokens/pares en los que esta ballena opera. Separados por comas. Ej: SOL,WIF,PEPE', max_length=500, null=True),
        ),
    ]
