# Generated by Django 5.2.7 on 2026-04-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_whalewallet_target_pairs'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhaleHuntTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain', models.CharField(choices=[('solana', 'Solana'), ('ethereum', 'Ethereum'), ('base', 'Base'), ('hyperliquid', 'Hyperliquid')], default='ethereum', max_length=50)),
                ('token_symbol', models.CharField(help_text='Símbolo del token. Ej: WIF, PEPE, BONK', max_length=20)),
                ('contract_address', models.CharField(help_text='Dirección del contrato del token', max_length=255)),
                ('min_volume_usd', models.FloatField(default=3000, help_text='Volumen mínimo en USD para considerar como ballena')),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar para pausar sin borrar')),
                ('notes', models.CharField(blank=True, help_text='Notas opcionales', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Whale Hunt Target',
                'verbose_name_plural': 'Whale Hunt Targets',
                'ordering': ['blockchain', 'token_symbol'],
                'unique_together': {('contract_address', 'blockchain')},
            },
        ),
    ]
