# Generated by Django 5.2.7 on 2026-04-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0033_whalehunttarget"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsensusSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_symbol", models.CharField(max_length=50)),
                ("blockchain", models.CharField(default="solana", max_length=50)),
                (
                    "whale_count",
                    models.IntegerField(
                        default=0,
                        help_text="Número de ballenas distintas que compraron",
                    ),
                ),
                (
                    "whale_addresses",
                    models.JSONField(
                        default=list,
                        help_text="Lista de wallets que dispararon la señal",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0, help_text="Confianza calculada entre 0 y 1"
                    ),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                (
                    "price_change_pct",
                    models.FloatField(
                        default=0.0, help_text="Cambio de precio desde la señal"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activa"),
                            ("EXPIRED", "Expirada"),
                            ("BOT_CREATED", "Bot Creado"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("alert_sent", models.BooleanField(default=False)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Consensus Signal",
                "verbose_name_plural": "Consensus Signals",
                "ordering": ["-detected_at"],
            },
        ),
    ]
