# Generated by Django 5.2.7 on 2026-04-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0034_consensus_signal"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhalePattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern_name", models.CharField(max_length=100)),
                (
                    "conditions",
                    models.JSONField(
                        help_text="Condiciones de indicadores ej: {'rsi_14__lt': 40, 'volume_ratio__gt': 1.5}"
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        default="4h",
                        help_text="Timeframe del contexto (1h, 4h, 1d)",
                        max_length=10,
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        default=0, help_text="Número de trades que cumplen este patrón"
                    ),
                ),
                (
                    "win_rate",
                    models.FloatField(default=0.0, help_text="Tasa de aciertos (0-1)"),
                ),
                (
                    "avg_pnl",
                    models.FloatField(default=0.0, help_text="PnL promedio en %"),
                ),
                (
                    "total_trades",
                    models.IntegerField(
                        default=0, help_text="Total trades analizados para este patrón"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si el patrón está activo para generar señales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whale Pattern",
                "verbose_name_plural": "Whale Patterns",
                "ordering": ["-win_rate", "-sample_size"],
            },
        ),
    ]
