# Generated by Django 5.2.7 on 2026-04-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_whalepattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(default='5m', max_length=5)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('volatility_score', models.FloatField(default=0)),
                ('volume_score', models.FloatField(default=0)),
                ('trend_score', models.FloatField(default=0)),
                ('signal_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('atr_pct', models.FloatField(help_text='ATR como % del precio', null=True)),
                ('volume_24h_usdt', models.FloatField(null=True)),
                ('adx_value', models.FloatField(null=True)),
                ('signals_found', models.JSONField(default=list)),
                ('recommended_strategy', models.CharField(blank=True, max_length=20, null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='dashboard.pair')),
            ],
            options={
                'verbose_name': 'Pair Scan Result',
                'verbose_name_plural': 'Pair Scan Results',
                'ordering': ['-total_score', '-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='ScalpAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(default='5m', max_length=5)),
                ('strategy', models.CharField(max_length=20)),
                ('signal_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], max_length=4)),
                ('price_at_alert', models.DecimalField(decimal_places=8, max_digits=20)),
                ('suggested_sl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('suggested_tp', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('indicators_snapshot', models.JSONField(blank=True, null=True)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scalp_alerts', to='dashboard.pair')),
            ],
            options={
                'verbose_name': 'Scalp Alert',
                'verbose_name_plural': 'Scalp Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScalpingBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strategy_type', models.CharField(choices=[('EMA_CROSS', 'EMA Cross (5/20) + Volumen'), ('BB_SQUEEZE', 'Bollinger Squeeze + Momentum'), ('VWAP_RSI', 'VWAP + RSI Bounce')], default='EMA_CROSS', max_length=20)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minuto'), ('3m', '3 Minutos'), ('5m', '5 Minutos'), ('15m', '15 Minutos')], default='5m', max_length=5)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='STOPPED', max_length=10)),
                ('is_live', models.BooleanField(default=False, help_text='Si True, ejecuta ordenes reales en Binance')),
                ('capital_usdt', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
                ('max_position_pct', models.DecimalField(decimal_places=2, default=50, help_text='% del capital por trade', max_digits=5)),
                ('sl_atr_mult', models.DecimalField(decimal_places=2, default=1.5, help_text='SL = N x ATR', max_digits=5)),
                ('tp_atr_mult', models.DecimalField(decimal_places=2, default=2.5, help_text='TP = N x ATR', max_digits=5)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('total_pnl_usdt', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scalping_bots', to='dashboard.pair')),
            ],
            options={
                'verbose_name': 'Scalping Bot',
                'verbose_name_plural': 'Scalping Bots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScalpingTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20)),
                ('take_profit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('pnl_usdt', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('pnl_pct', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED_TP', 'Cerrada (Take Profit)'), ('CLOSED_SL', 'Cerrada (Stop Loss)'), ('CLOSED_MANUAL', 'Cerrada (Manual)')], default='OPEN', max_length=20)),
                ('entry_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('exit_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('indicators_snapshot', models.JSONField(blank=True, null=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='dashboard.scalpingbot')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
    ]
