# Generated by Django 5.2.7 on 2026-04-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0036_pairscanresult_scalpalert_scalpingbot_scalpingtrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="auto_scalp_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Habilita la creación y ejecución automática de bots SIMULADOS de scalping.",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="auto_scalp_min_conf",
            field=models.DecimalField(
                decimal_places=2,
                default=75.0,
                help_text="Porcentaje de confianza mínima requerida (>X) para detonar un nuevo bot.",
                max_digits=5,
            ),
        ),
    ]
