# Generated by Django 5.2.7 on 2026-04-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_globalsettings_auto_scalp_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalpalert',
            name='bot_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scalpalert',
            name='bot_creation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
